// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auth "go-auth-app/modules/auth"
	user "go-auth-app/modules/user"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

func (_m *AuthService) ForgotPassword(email string) error {
	ret := _m.Called(email)
	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}
	if rf, ok := ret.Get(0).(func(string) error); ok {
		return rf(email)
	}
	return ret.Error(0)
}

func (_m *AuthService) GetProfile(userID uint) (*user.User, error) {
	ret := _m.Called(userID)
	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}
	var r0 *user.User
	if rf, ok := ret.Get(0).(func(uint) (*user.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *user.User); ok {
		r0 = rf(userID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*user.User)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *AuthService) Login(email string, password string, deviceID string, userAgent string, ipAddress string) (*auth.AuthTokens, error) {
	ret := _m.Called(email, password, deviceID, userAgent, ipAddress)
	if len(ret) == 0 {
		panic("no return value specified for Login")
	}
	var r0 *auth.AuthTokens
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) (*auth.AuthTokens, error)); ok {
		return rf(email, password, deviceID, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) *auth.AuthTokens); ok {
		r0 = rf(email, password, deviceID, userAgent, ipAddress)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*auth.AuthTokens)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(email, password, deviceID, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *AuthService) Logout(userID uint, deviceID string) error {
	ret := _m.Called(userID, deviceID)
	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		return rf(userID, deviceID)
	}
	return ret.Error(0)
}

func (_m *AuthService) RefreshToken(oldRefreshToken string) (*auth.AuthTokens, error) {
	ret := _m.Called(oldRefreshToken)
	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}
	var r0 *auth.AuthTokens
	if rf, ok := ret.Get(0).(func(string) (*auth.AuthTokens, error)); ok {
		return rf(oldRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.AuthTokens); ok {
		r0 = rf(oldRefreshToken)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*auth.AuthTokens)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(oldRefreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *AuthService) Register(in *user.User, password string) error {
	ret := _m.Called(in, password)
	if len(ret) == 0 {
		panic("no return value specified for Register")
	}
	if rf, ok := ret.Get(0).(func(*user.User, string) error); ok {
		return rf(in, password)
	}
	return ret.Error(0)
}

func (_m *AuthService) ResendVerification(email string) error {
	ret := _m.Called(email)
	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}
	if rf, ok := ret.Get(0).(func(string) error); ok {
		return rf(email)
	}
	return ret.Error(0)
}

func (_m *AuthService) ResetPassword(token string, newPassword string) error {
	ret := _m.Called(token, newPassword)
	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		return rf(token, newPassword)
	}
	return ret.Error(0)
}

func (_m *AuthService) SocialLogin(provider string, idToken string, deviceID string, userAgent string, ipAddress string) (*auth.AuthTokens, error) {
	ret := _m.Called(provider, idToken, deviceID, userAgent, ipAddress)
	if len(ret) == 0 {
		panic("no return value specified for SocialLogin")
	}
	var r0 *auth.AuthTokens
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) (*auth.AuthTokens, error)); ok {
		return rf(provider, idToken, deviceID, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) *auth.AuthTokens); ok {
		r0 = rf(provider, idToken, deviceID, userAgent, ipAddress)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*auth.AuthTokens)
	}
	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(provider, idToken, deviceID, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (_m *AuthService) VerifyEmail(token string) error {
	ret := _m.Called(token)
	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}
	if rf, ok := ret.Get(0).(func(string) error); ok {
		return rf(token)
	}
	return ret.Error(0)
}

func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)
	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}
