// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "go-auth-app/models"

	mock "github.com/stretchr/testify/mock"

	services "go-auth-app/services"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// GetProfile provides a mock function with given fields: userID
func (_m *AuthService) GetProfile(userID uint) (*models.User, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*models.User, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *models.User); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password, deviceID, userAgent, ipAddress
func (_m *AuthService) Login(email string, password string, deviceID string, userAgent string, ipAddress string) (*services.AuthTokens, error) {
	ret := _m.Called(email, password, deviceID, userAgent, ipAddress)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *services.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) (*services.AuthTokens, error)); ok {
		return rf(email, password, deviceID, userAgent, ipAddress)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string, string) *services.AuthTokens); ok {
		r0 = rf(email, password, deviceID, userAgent, ipAddress)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string, string) error); ok {
		r1 = rf(email, password, deviceID, userAgent, ipAddress)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: userID, deviceID
func (_m *AuthService) Logout(userID uint, deviceID string) error {
	ret := _m.Called(userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(userID, deviceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: oldRefreshToken
func (_m *AuthService) RefreshToken(oldRefreshToken string) (*services.AuthTokens, error) {
	ret := _m.Called(oldRefreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *services.AuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*services.AuthTokens, error)); ok {
		return rf(oldRefreshToken)
	}
	if rf, ok := ret.Get(0).(func(string) *services.AuthTokens); ok {
		r0 = rf(oldRefreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.AuthTokens)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(oldRefreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: user, password
func (_m *AuthService) Register(user *models.User, password string) error {
	ret := _m.Called(user, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.User, string) error); ok {
		r0 = rf(user, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResendVerification provides a mock function with given fields: email
func (_m *AuthService) ResendVerification(email string) error {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyEmail provides a mock function with given fields: token
func (_m *AuthService) VerifyEmail(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
