// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "go-auth-app/models"

	mock "github.com/stretchr/testify/mock"
)

// EmailVerificationTokenRepository is an autogenerated mock type for the EmailVerificationTokenRepository type
type EmailVerificationTokenRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: token
func (_m *EmailVerificationTokenRepository) Create(token *models.EmailVerificationToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.EmailVerificationToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: id
func (_m *EmailVerificationTokenRepository) DeleteByID(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUserID provides a mock function with given fields: userID
func (_m *EmailVerificationTokenRepository) DeleteByUserID(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByToken provides a mock function with given fields: token
func (_m *EmailVerificationTokenRepository) FindByToken(token string) (*models.EmailVerificationToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *models.EmailVerificationToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.EmailVerificationToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.EmailVerificationToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.EmailVerificationToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEmailVerificationTokenRepository creates a new instance of EmailVerificationTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailVerificationTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailVerificationTokenRepository {
	mock := &EmailVerificationTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
