// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "go-auth-app/models"

	mock "github.com/stretchr/testify/mock"
)

// PasswordResetRepository is an autogenerated mock type for the PasswordResetRepository type
type PasswordResetRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: token
func (_m *PasswordResetRepository) Create(token *models.PasswordResetToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.PasswordResetToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: token
func (_m *PasswordResetRepository) Delete(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByToken provides a mock function with given fields: token
func (_m *PasswordResetRepository) FindByToken(token string) (*models.PasswordResetToken, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *models.PasswordResetToken
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.PasswordResetToken, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(string) *models.PasswordResetToken); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PasswordResetToken)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPasswordResetRepository creates a new instance of PasswordResetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPasswordResetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PasswordResetRepository {
	mock := &PasswordResetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
