// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "go-auth-app/models"

	mock "github.com/stretchr/testify/mock"
)

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

// DeleteByID provides a mock function with given fields: id
func (_m *RefreshTokenRepository) DeleteByID(id uint) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByUser provides a mock function with given fields: userID
func (_m *RefreshTokenRepository) DeleteByUser(userID uint) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByUser provides a mock function with given fields: userID
func (_m *RefreshTokenRepository) FindByUser(userID uint) ([]models.RefreshToken, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUser")
	}

	var r0 []models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.RefreshToken, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.RefreshToken); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByUserAndDevice provides a mock function with given fields: userID, deviceID
func (_m *RefreshTokenRepository) FindByUserAndDevice(userID uint, deviceID string) (*models.RefreshToken, error) {
	ret := _m.Called(userID, deviceID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserAndDevice")
	}

	var r0 *models.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, string) (*models.RefreshToken, error)); ok {
		return rf(userID, deviceID)
	}
	if rf, ok := ret.Get(0).(func(uint, string) *models.RefreshToken); ok {
		r0 = rf(userID, deviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, string) error); ok {
		r1 = rf(userID, deviceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: token
func (_m *RefreshTokenRepository) Save(token *models.RefreshToken) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.RefreshToken) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
